version: '3'
services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: vcp_postgres
    environment:
      POSTGRES_DB: vcp_demo
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"

volumes:
  postgres-data:
